### ISSUE TITLE
Missing: net.fabricmc:fabric-loom-ninjaphenix:0.2.6-SNAPSHOT

### ISSUE THREAD

**Issue by ezonius** [NinjaPhenix/expandedstorageapi#1]
Can't seem to find the code for your fabric-loom-ninjaphenix in your fabric-loom repository. 

If it's not on Github, could you push it to github? would like to compile this locally so I can update your expanded storage mod latest snapshots.

**Comment by NinjaPhenix** [comment]
I'm actually in the process of updating right now, also you can just use the regular loom.

**Comment by ezonius** [comment]
Alright, I'll give that a shot. Thanks
